name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Deploy files to DigitalOcean
        uses: appleboy/scp-action@v0.1.1
        with:
          host: 104.248.38.196
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          source: "./"
          target: "/var/www/html"
          ssh_args: "-o StrictHostKeyChecking=no"
