name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy files to DigitalOcean
        uses: appleboy/scp-action@v0.1.1
        with:
          host: your_droplet_ip
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          source: "./"
          target: "/var/www/html"
