name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test SSH Connection to DigitalOcean
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 104.248.38.196
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            echo "SSH Connection Successful" && ls /var/www/html
